### Question-1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
array = np.arange(2, 50, 3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Question-2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [16]:
import numpy as np
list1 = []
list2 = []

print("Enter List1:")
for i in range(5):
    num = int(input())
    list1.append(num)

print("Enter List2:")
for i in range(5):
    num = int(input())
    list2.append(num)

array1 = np.array(list1)
array2 = np.array(list2)

concat_array = np.concatenate((array1, array2))
print(concat_array)
print(np.sort(concat_array))

Enter List1:
3
5
6
1
2
Enter List2:
4
8
3
5
1
[3 5 6 1 2 4 8 3 5 1]
[1 1 2 3 3 4 5 5 6 8]


### Question-3

Write a code snippet to find the dimensions of a ndarray and its size.

In [25]:
import numpy as np
array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array.ndim)
print(array.size)

3
8


### Question-4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [6]:
import numpy as np
array = np.arange(9)
newarray = array.reshape(3,3)
print(newarray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In above code, reshape contain 2 parameters
 - first parameter: dimensions like row size
 - second parameter: number of elements like column size
dimension and element number need to match with array size

if array size is 8 and tried to (3,3) then it will not be allowed (it requires 3*3 = 9 array size)

### Question-5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [8]:
import numpy as np
array1 = np.square([[1,2,3],[4,5,6]])
array2 = np.square([[7,8,9],[10,11,12]])
print(np.vstack((array1, array2)))
print(np.hstack((array1, array2)))

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[  1   4   9  49  64  81]
 [ 16  25  36 100 121 144]]


### Question-6

How to get unique items and counts of unique items?

In [9]:
import numpy as np
array = np.array([1,2,3,2,4,8,3,1])
unique, count = np.unique(array, return_counts = True)
print(unique)
print(count)

[1 2 3 4 8]
[2 2 2 1 1]
